include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - always_declare_return_types
    - camel_case_types
    - annotate_overrides
    - constant_identifier_names
    - one_member_abstracts
    - sort_constructors_first
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - unnecessary_this
    